In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [27]:
hd_df=pd.read_excel('heart_disease.xlsx',sheet_name='Heart_disease')
hd_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,thal,num
0,63,Male,typical angina,145,233,True,lv hypertrophy,150,False,2.3,downsloping,fixed defect,0
1,41,Male,atypical angina,135,203,False,normal,132,False,0.0,flat,fixed defect,0
2,57,Male,asymptomatic,140,192,False,normal,148,False,0.4,flat,fixed defect,0
3,52,Male,typical angina,118,186,False,lv hypertrophy,190,False,0.0,flat,fixed defect,0
4,57,Male,asymptomatic,110,201,False,normal,126,True,1.5,flat,fixed defect,0

In [28]:
hd_df.fbs=hd_df.fbs.astype(str)
#hd_df.exang=hd_df.exang.astype(str)

In [29]:
lenc=preprocessing.LabelEncoder()
hd_df[['fbs','exang']]=hd_df[['fbs','exang']].apply(lenc.fit_transform)

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['bool', 'str']

In [23]:
hd_df.exang.dtype

dtype('O')

In [19]:
hd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       908 non-null    int64
 1   sex       908 non-null    object
 2   cp        908 non-null    object
 3   trestbps  908 non-null    int64
 4   chol      908 non-null    int64
 5   fbs       908 non-null    bool
 6   restecg   908 non-null    object
 7   thalch    908 non-null    int64
 8   exang     908 non-null    object
 9   oldpeak   846 non-null    float64
 10  slope     908 non-null    object
 11  thal      908 non-null    object
 12  num       908 non-null    int64
dtypes: bool(1), float64(1), int64(5), object(6)
memory usage: 86.1+ KB

In [21]:
hd_df.replace({'exang':{True:1,'TURE':1,'FALSE':0,False:0}})#,inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,thal,num
0,63,Male,typical angina,145,233,True,lv hypertrophy,150,0,2.3,downsloping,fixed defect,0
1,41,Male,atypical angina,135,203,False,normal,132,0,0.0,flat,fixed defect,0
2,57,Male,asymptomatic,140,192,False,normal,148,0,0.4,flat,fixed defect,0
3,52,Male,typical angina,118,186,False,lv hypertrophy,190,0,0.0,flat,fixed defect,0
4,57,Male,asymptomatic,110,201,False,normal,126,1,1.5,flat,fixed defect,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,53,Male,asymptomatic,125,0,False,normal,120,0,1.5,upsloping,reversable defect,4
904,62,Male,asymptomatic,166,170,False,st-t abnormality,120,1,3.0,flat,reversable defect,4
905,56,Male,non-anginal,170,0,False,lv hypertrophy,123,1,2.5,downsloping,normal,4
906,56,Male,non-anginal,144,208,True,st-t abnormality,105,1,NaN,downsloping,fixed defect,4
907,57,Male,asymptomatic,142,277,True,st-t abnormality,182,0,NaN,flat,reversable defect,4

In [5]:
hd_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,thal,num
0,63,Male,typical angina,145,233,True,lv hypertrophy,150,False,2.3,downsloping,fixed defect,0
1,41,Male,atypical angina,135,203,False,normal,132,False,0.0,flat,fixed defect,0
2,57,Male,asymptomatic,140,192,False,normal,148,False,0.4,flat,fixed defect,0
3,52,Male,typical angina,118,186,False,lv hypertrophy,190,False,0.0,flat,fixed defect,0
4,57,Male,asymptomatic,110,201,False,normal,126,True,1.5,flat,fixed defect,0